<a href="https://colab.research.google.com/github/fxop0218/PyTorchForBeginners/blob/main/pytorch_for_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch for beginers

This booklet aims to show the first steps to follow when creating a model with pytorch and its main features.

In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.13.0+cu116


# 🟦EN Introducton to Tensors

# 🟥ES Introducción a los tensores.

### Creating tensors

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

To see more information of  [Pytotch tensors](https://pytorch.org/docs/stable/tensors.html)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor as Python int
scalar.item()

7

In [5]:
# Vector
vec = torch.tensor([7,7])
vec

tensor([7, 7])

In [6]:
vec.ndim

1

In [7]:
vec.shape

torch.Size([2])

In [8]:
# Matrix

matrix = torch.tensor([[1,1],
                       [2,1]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
matrix[1]

tensor([2, 1])

In [12]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                        [3,5,7],
                        [1,2,3]]])

tensor

tensor([[[1, 2, 3],
         [3, 5, 7],
         [1, 2, 3]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

***🟦EN*** The first number (x) of torch.Size([x, y, z]) means the number of dimensions of the matrix, the second number (y), represents the number of vectors that compose the matrix, and the last number (z) means reflects the number of numbers that are in the matrix per neighbor, and the last number (z) means the number of vectors that compose the matrix.

***🟥ES*** El primer numero(x) de torch.Size([x, y, z]) significa el numero de dimensiones de la matriz, en segundo numero (y), representa el número de vectores que componen la matriz, y el ultimo número (z) significa refleja la cantidad de números que hay por vec

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [3, 5, 7],
        [1, 2, 3]])

In [16]:
tensor[0][0]

tensor([1, 2, 3])

In [17]:
tensor[0][0][0]

tensor(1)

## Random tensors

***🟦EN***:The random tensors are important becuase the way many neuronal networks learn is that they start with ramdom number in their tensors and adjus those to better represent the data. 


***🟥ES***:Los tensores aleatorios son importantes porque la forma en que muchas redes neuronales aprenden es que empiezan con números aleatorios en sus tensores y los ajustan para representar mejor los datos. 

In [18]:
# Create random tensor of size [3, 4]
rand_tensor = torch.rand(3, 4)
rand_tensor

tensor([[0.1357, 0.6940, 0.5625, 0.8715],
        [0.8947, 0.9559, 0.9125, 0.2577],
        [0.2389, 0.0158, 0.3433, 0.8495]])

In [19]:
rand_tensor2 = torch.rand(7, 2, 2)
rand_tensor2

tensor([[[0.1715, 0.4594],
         [0.7946, 0.2944]],

        [[0.1224, 0.8873],
         [0.7992, 0.3094]],

        [[0.2040, 0.6843],
         [0.6679, 0.1653]],

        [[0.1418, 0.7375],
         [0.6067, 0.4060]],

        [[0.0963, 0.2255],
         [0.8632, 0.1235]],

        [[0.5176, 0.2962],
         [0.0868, 0.6849]],

        [[0.1959, 0.8998],
         [0.6275, 0.0611]]])

In [20]:
# Create random tensor with similar shapo to an imgae
HEIGHT = 224
WIDTH = 224
COLOR = 3 # Black and with = 1
rand_img_tensor = torch.rand(size=(HEIGHT, WIDTH, COLOR)) # height, width, RGB (in this case)
print(f"Shape: {rand_img_tensor.shape}\nNDIM: {rand_img_tensor.ndim}\nDType: {rand_img_tensor.dtype}")

Shape: torch.Size([224, 224, 3])
NDIM: 3
DType: torch.float32


In [21]:
# Tensor all zeros
zero_tensor = torch.zeros(size=(3, 4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Tensor all one
one_tensor = torch.ones(size=(4,4))
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Create a range of tensors and tensors-like

In [23]:
arange_ = torch.arange(0, 10)
# To 1 - 10:
one_ten = torch.arange(1, 11)
one_ten

print(f"arange(0,10): {arange_}\n arange(1, 11): {one_ten}")

arange(0,10): tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 arange(1, 11): tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [24]:
step = torch.arange(start=0, end=3000, step=94)
step

tensor([   0,   94,  188,  282,  376,  470,  564,  658,  752,  846,  940, 1034,
        1128, 1222, 1316, 1410, 1504, 1598, 1692, 1786, 1880, 1974, 2068, 2162,
        2256, 2350, 2444, 2538, 2632, 2726, 2820, 2914])

In [25]:
# tensor-like (Transform all the numbers to 0)
ten_zeros = torch.zeros_like(input=one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

***🟦EN***: Datatypes is a common error in DeepLearnig con PyTorch

***🟥ES***: Los Datatypes son un error comun en DeepLearnign con PyTorch

***🟦EN***: The principal error in are:
1. Tensor no rigth datatype.
2. Tensor not right shape.
3. Tensor not right device.

***🟥ES***: Los principales errores són:
1. Tensors sin el datatype correcto
2. Tensor no tiene la forma correcta
3. Tensor sin el dispositivo correcto.

In [26]:
# float32 tensor

f_32_tensor = torch.tensor([3.0, 5.0, 6.0], dtype=None,
                           device=None,
                           requires_grad=False) 
f_32_tensor
# If dtype is not specificated the default dtype is float32

tensor([3., 5., 6.])

In [27]:
tensor_correct = torch.tensor([3.0, 2.0, 1.0],
                              dtype=None,
                              device="cpu", # cuda with gpu
                              requires_grad=False)
tensor_correct

tensor([3., 2., 1.])

In [28]:
print(f"DataType: {tensor_correct.dtype}")

DataType: torch.float32


### Get information from tensors
1. Tensor no rigth datatype -- To do get datatype from tensor, can use ```tensor.dtype```
2. Tensor not right shape -- To get shape from a tensor, can use `tensor.shape`
3. Tensor not right device -- To get devide from a tensor, can use `tensor.device`

In [29]:
ex_tensor = torch.rand(4,4)
ex_tensor

tensor([[0.8627, 0.7803, 0.2168, 0.6580],
        [0.1702, 0.2578, 0.9790, 0.7919],
        [0.3391, 0.2280, 0.4141, 0.3450],
        [0.1115, 0.0374, 0.7620, 0.0518]])

In [30]:
# Get details form a tensor
print(f"{ex_tensor}\nDataType: {ex_tensor.dtype}\nShapeTensor: {ex_tensor.shape}\nDevice: {ex_tensor.device}")

tensor([[0.8627, 0.7803, 0.2168, 0.6580],
        [0.1702, 0.2578, 0.9790, 0.7919],
        [0.3391, 0.2280, 0.4141, 0.3450],
        [0.1115, 0.0374, 0.7620, 0.0518]])
DataType: torch.float32
ShapeTensor: torch.Size([4, 4])
Device: cpu


### Editic tensors

Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [31]:
ten = torch.tensor([12, 2, 5])

In [32]:
# Create a tensor
%%time
print(f"Default tensor: {ten}\nTensor adding 10: {ten + 10}\nTensor muliply per 10: {ten * 10}\nSubstract 10: {ten - 10}")

Default tensor: tensor([12,  2,  5])
Tensor adding 10: tensor([22, 12, 15])
Tensor muliply per 10: tensor([120,  20,  50])
Substract 10: tensor([ 2, -8, -5])
CPU times: user 3.1 ms, sys: 1.02 ms, total: 4.12 ms
Wall time: 10.1 ms


In [33]:
# Using PyTorch funtions to do the same
%%time
print(f"Default tensor: {ten}\nTensor adding 10: {torch.add(ten, 10)}\nTensor muliply per 10: {torch.mul(ten, 10)}\nSubstract 10: {torch.sub(ten, 10)}")

Default tensor: tensor([12,  2,  5])
Tensor adding 10: tensor([22, 12, 15])
Tensor muliply per 10: tensor([120,  20,  50])
Substract 10: tensor([ 2, -8, -5])
CPU times: user 1.32 ms, sys: 0 ns, total: 1.32 ms
Wall time: 2.79 ms


### Matrix multiplication

Two main ways of performing multiplications in NN (Neuronal networks) & DL (Deep learning):

1. Matrix multiplication (IMPORTANT)
2. Element-wise multiplication

In [34]:
# Element wise multiplication

print(f"{ten} * {ten} = {ten * ten}\n#################\nPytorch funcion: {torch.matmul(ten, ten)}")

tensor([12,  2,  5]) * tensor([12,  2,  5]) = tensor([144,   4,  25])
#################
Pytorch funcion: 173


***🟦EN***: Let's see the time dif usign matmul and to do it by hand

***🟥ES***: Vamos a ver la diferencia aciendolo usando matmaul o haciendolo a mano.

In [35]:
# Matrix mult by hand
%%time
val = 0
for i in range(len(ten)):
  val += ten[i] * ten[i]
print(val)

tensor(173)
CPU times: user 2.29 ms, sys: 40 µs, total: 2.33 ms
Wall time: 5.19 ms


In [36]:
%%time
torch.matmul(ten, ten) # is the same as torch.mm(x, x)

CPU times: user 82 µs, sys: 0 ns, total: 82 µs
Wall time: 246 µs


tensor(173)

Two main rules that performing matrix multiplication needs to satisfy:
1. The *inner dimensions* must match:
* `(3, 2) @ (3, 2)` Must work
* `(7, 3) @ (3, 7)` Works
* `(4, 2) @ (2, 4)` Works
The resutl matrix has teh shape of the *outer dimension*
* `(2, 3) @ (3, 2)` ==> `(2, 2)`
* `(7, 3) @ (3, 7)` ==> `(7, 7)`

In [37]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.8575, 0.8629, 0.7787],
        [0.2069, 0.3861, 0.3229],
        [0.2114, 0.4921, 0.4040]])

In [38]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

### Common error in deep learnin => Shape errors

In [39]:
# Shape for matrix => See the proccess http://matrixmultiplication.xyz/
tensor1 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor2 = torch.tensor([[7, 8],
                        [9, 5],
                        [3, 2]])


***🟦EN***: In this case we can't multiply `tensor1` per `tensor2`, to manipulte the shape of on eof our tensors using a **transpose**, this funciton, switches the dimension of a given tensor.

***🟥ES***: Es este caso, no podemos multiplicat el `tensor1` por el `tensor2`, para manipualr la dimension de uno de los tensores usaremos la funcion **transpose**, esta dimensión intercambia la dimensión del tensor dado.

In [40]:
print(f"Default tensor: {tensor1}\nTrasosed tensor: {tensor1.T}\nShape of default tensor {tensor1.shape}\nTransposed shape: {tensor1.T.shape}")

Default tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])
Trasosed tensor: tensor([[1, 3, 5],
        [2, 4, 6]])
Shape of default tensor torch.Size([3, 2])
Transposed shape: torch.Size([2, 3])


In [41]:
# Now can multiplication works when the tensor2 is transposed

torch.mm(tensor1, tensor2.T)

tensor([[23, 19,  7],
        [53, 47, 17],
        [83, 75, 27]])

## Find th max, min, mean, sum...(tensor aggregation)


In [42]:
# Tensor creation

tensor = torch.arange(0, 100, 5)
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [43]:
print(f"Max: {torch.max(tensor)} // {tensor.max()}\nMin: {torch.min(tensor)} // {tensor.min()}")

# If we try to average this tensor, we will get an error due to an incorrect datatype.

tensor.dtype # https://pytorch.org/docs/stable/generated/torch.mean.html

Max: 95 // 95
Min: 0 // 0


torch.int64

In [44]:
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(47.5000), tensor(47.5000))

In [45]:
# Find the sum
torch.sum(tensor), tensor.sum()

(tensor(950), tensor(950))

In [46]:
print(f"ArgMin: {tensor.argmin()} ArgMax: {tensor.argmax()}")

ArgMin: 0 ArgMax: 19


## Reshaping, stackng, squeezing and unsequeezing tensors.

***🟦EN***: 
* **Reshaping**: Reshapes an input tensor to a defined shape.
* **View**: Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* **Stacking**: Combine multiple tensors on top of each other (vstack) or side by side. 
* **Squeeze**: Removes all `1` dimensions from a tensor
* **Unsqueeze**: Add a `1` dimension to a target tensor
* **Permute**: Return a view of the input with dimensions permuted (swapped) in a certain way

***🟥ES***:
* **Reshaping**: Da nueva forma a un tensor de entrada con una forma definida.
* **View**: Devuelve una vista de un tensor de entrada de cierta forma pero manteniendo la misma memoria que el tensor original.
* **Stacking**: Combina varios tensores uno encima de otro (vstack) o uno al lado del otro.
* **Unsqueeze**: Añade `1` dimension al tensor escogido.
* **Permute**: Devuelve una vista de la entrada con las dimensiones permutadas (intercambiadas) de una determinada manera.

In [47]:
# Create a tensor

tensor = torch.arange(1., 11.)
print(f"Tensor: {tensor}\nTensor Shape: {tensor.shape}")

Tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Tensor Shape: torch.Size([10])


In [48]:
# Now we add an extra dimension to the last tensor.
tensor_reshaped = tensor.reshape(1, 10) # tensor.reshape(x, y) To reshape y we need the form sama has te tensor.
print(f"Reshaped tensor: {tensor_reshaped}\nReshaped tensor shape: {tensor_reshaped.shape}")

Reshaped tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Reshaped tensor shape: torch.Size([1, 10])


In [49]:
tensor_reshaped = tensor.reshape(10, 1) # tensor.reshape(x, y) To reshape x we need the form sama has te tensor.
print(f"Reshaped tensor: {tensor_reshaped}\nReshaped tensor shape: {tensor_reshaped.shape}")

Reshaped tensor: tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
Reshaped tensor shape: torch.Size([10, 1])


In [50]:
tensor_reshaped = tensor.reshape(5, 2) # tensor.reshape(x, y) To reshape x we need the form sama has te tensor.
print(f"Reshaped tensor: {tensor_reshaped}\nReshaped tensor shape: {tensor_reshaped.shape}")

Reshaped tensor: tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
Reshaped tensor shape: torch.Size([5, 2])


In [51]:
# Change the view 

cv_tensor = tensor.view(1,10)
print(f"Changed view tensor: {cv_tensor}\nDefault tensor: {tensor}")

Changed view tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Default tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [52]:
# Changin cv_tensor changes tensor variable, becuase a view of a tensor shaes the same memory as the original imput.
cv_tensor[:, 0] = 5
print(f"Changed view tensor: {cv_tensor}\nDefault tensor: {tensor}")

Changed view tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Default tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [53]:
# Stack tensors on top of each other
tensor_stacked = torch.stack([tensor, tensor, tensor, tensor])
tensor_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [54]:
tensor_stacked = torch.stack([tensor, tensor, tensor, tensor], dim=1)
tensor_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [55]:
# torch.squeezee() removes all single dimensions forma target tensor.
print(f"Tensor before squeeze: {cv_tensor}\nTensor before squeeze shape: {cv_tensor.shape}")
squeeze_tensor = cv_tensor.squeeze()
print("###############################")
print(f"Tensor after squeeze: {squeeze_tensor}\nTensor after squeeze shape: {squeeze_tensor.shape}")

Tensor before squeeze: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Tensor before squeeze shape: torch.Size([1, 10])
###############################
Tensor after squeeze: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Tensor after squeeze shape: torch.Size([10])


In [56]:
# Add extradimension with unsqueeze
unsqueezed_tensor = squeeze_tensor.unsqueeze(dim=0) # dim = 1 ==> torch.shape([10, 1])
print(f"New tensor: {unsqueezed_tensor}")
print(f"New shape: {unsqueezed_tensor.shape}")

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [57]:
# torch.permute ==> rearranges the dimensions of a target tensor in a specidied order

original = torch.rand(size=(224, 224, 3)) # Height, width, colour cannels

# Permute the original tensor to rearrange the axis (or dim) order

permuted = original.permute(2, 0, 1) # Shifts axis 0 => 1, 1 => 2, 2 => 0

print(f"Previous shape: {original.shape}\nNew shape: {permuted.shape}") # Colour cannels, Height, width 

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [58]:
# The changes in the "original" are reflected in the "permuted" becuase share the space of memory
permuted[0, 0, 0] = 10
print(f"Prtmuted: {permuted[0,0,0]}\nOriginal: {original[0,0,0]}")

Prtmuted: 10.0
Original: 10.0


### Indexin (select data from tensors) *Similar to NumPy*

***🟦EN***: Indexin with Pytorch in very similar to indexing with NumPy

***🟥ES***: Indexar con PyTorch es muy similar a indexar con NumPy

In [59]:
# Create a tensor

tensor_idx = torch.arange(1, 10).reshape(1, 3, 3)
print(f"Tensor: {tensor_idx}\nTensor shape: {tensor_idx.shape}")

Tensor: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Tensor shape: torch.Size([1, 3, 3])


In [60]:
print(f"{tensor_idx[0]}\n{tensor_idx[0][0]}")

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])


In [61]:
# Let0s index on the most inner braket (last dimension)
tensor_idx[0][0][0], tensor_idx[0][1][1]

(tensor(1), tensor(5))

In [62]:
# To select all of a target dimension, we use :
tensor_idx[:, 2]

tensor([[7, 8, 9]])

In [63]:
# Get all the values of 0th and 1st dimensions but only index 1 of 2nd dimension
tensor_idx[:, :, 1]

tensor([[2, 5, 8]])

In [64]:
# Get all values of the 0 dimension but only the 1 index values of 1st and 2nd dimesnion
tensor_idx[:, 1, 1]

tensor([5])

In [65]:
# Index to return 9
tensor_idx[:, 2, 2]

tensor([9])

In [66]:
# Index to return 3, 6, 9
tensor_idx[:, :, 2]

tensor([[3, 6, 9]])

### Pytorch & NumPy

***🟦EN***: NumPy its a popular library to numerical computing, and becuase of this, PyTorch can interact with him.
* Data in **NumPy**, want in PyTorch tensor => `torch.from_numpy(ndarray)`
* **PyTorch** tensor to NumPy => `torch.Tensor.numpy()`

***🟥ES***: NumPy es una biblioteca popular para la computación numérica, y debido a esto, PyTorch puede interactuar con él
* Datos en **NumPy**, a **PyTorch** tensro => `torch.from_numpy(ndarray)`
* **PyTorch** Tensor a **NumPy** => `torch.Tensor.numpy()`

In [67]:
# NUMPY ARRAY TO PYTORCH TENSOR
# Imports
import torch
import numpy as np

# Create array
array = np.arange(1.0, 8.0)

# Transform to tensor
tensor = torch.from_numpy(array) # The default datatype when we are transformed from numpy to tensor is float64

print(f"Array: {array}\nTensor: {tensor}")
print(f"Array DType: {array.dtype}\nTensor DType: {tensor.dtype}")

Array: [1. 2. 3. 4. 5. 6. 7.]
Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
Array DType: float64
Tensor DType: torch.float64


In [68]:
# PYTORCH TENSOR TO NUMPY ARRAY
# Imports
import torch
import numpy as np

# Create a tensro
tensor = torch.arange(1.0, 10.0)

# To array
array = tensor.numpy()

print(f"Array: {array}\nTensor: {tensor}")
print(f"Array DType: {array.dtype}\nTensor DType: {tensor.dtype}")

Array: [1. 2. 3. 4. 5. 6. 7. 8. 9.]
Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Array DType: float32
Tensor DType: torch.float32


### Reproducbility (trying to take random out of random)

***🟦EN***: In short how a neural network learns:

Start with random numbers => tensor operations => update random numbers to try and make them better representations of data => repeat

To reduce the randomness in NN we use a *Random seed*.

***🟥ES***: En resumen, cómo aprende una red neuronal:

Empieza con números aleatorios => operaciones tensoriales => actualiza los números aleatorios para intentar que representen mejor los datos => repite

Para reducir la aleatoriedad en las NN, usamos una *Semilla aleatoría*

In [69]:
# Imports
import torch

# Create a random tensor
rand_tensor1 = torch.rand(3, 5)
rand_tensor2 = torch.rand(3, 5)

# Show
print(f"Random tensor 1:\n{rand_tensor1}\nRandom tensor 2:\n{rand_tensor2}\nThe tensors are the same?\n{rand_tensor1 == rand_tensor2}")

Random tensor 1:
tensor([[0.7621, 0.0943, 0.0326, 0.7796, 0.9931],
        [0.9711, 0.3766, 0.0466, 0.4129, 0.3991],
        [0.9663, 0.3513, 0.4921, 0.6189, 0.7522]])
Random tensor 2:
tensor([[0.7942, 0.6972, 0.7532, 0.7129, 0.0548],
        [0.6718, 0.2428, 0.7385, 0.7523, 0.5954],
        [0.3981, 0.1782, 0.9675, 0.8670, 0.0604]])
The tensors are the same?
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [70]:
# Make reproducible "ramdom tensors"
# Imports

import torch

# Create random seed
RANDOM_SEED = 1000

# Create "Random" tensor
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 5)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 5)

print(f"Random tensor 1:\n{random_tensor_A}\nRandom tensor 2:\n{random_tensor_B}\nThe tensors are the same?\n{random_tensor_A == random_tensor_B}")

Random tensor 1:
tensor([[0.3189, 0.6136, 0.4418, 0.2580, 0.2724],
        [0.6261, 0.4410, 0.3653, 0.3535, 0.5971],
        [0.3572, 0.4807, 0.4217, 0.1254, 0.6818]])
Random tensor 2:
tensor([[0.3189, 0.6136, 0.4418, 0.2580, 0.2724],
        [0.6261, 0.4410, 0.3653, 0.3535, 0.5971],
        [0.3572, 0.4807, 0.4217, 0.1254, 0.6818]])
The tensors are the same?
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


### Running tensors on the GPUs
***🟦EN***: The GPUs enable much faster computing thanks to CUDA and NVIDIA technologies.

***🟥ES***: Las GPUs permiten una computación mucho mas rapida gracias a las tecnologias CUDA y de NVIDIA.

In [71]:
# Check if have access to a GPU
import torch

torch.cuda.is_available()

False

In [72]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [73]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [74]:
# Number of devices

torch.cuda.device_count()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0